
  CREATE TABLE "PRODUCTS" 
   (	"PRODUCT_CODE" NUMBER(5,0), 
	"CATEGORY" VARCHAR2(10) NOT NULL ENABLE, 
	"PRODUCT_NAME" VARCHAR2(200) NOT NULL ENABLE, 
	"PRODUCT_COLOR" VARCHAR2(20), 
	"PRODUCT_SIZE" VARCHAR2(20), 
	"STATUS" VARCHAR2(10) NOT NULL ENABLE, 
	"AMOUNT" NUMBER(3,0), 
	"ORIGINAL_PRICE" NUMBER(7,0), 
	"DISCOUNT" NUMBER(7,0), 
	"MULTI_PURCHASE_DISCOUNT" NUMBER(7,0), 
	"DISCOUNT_RATE" NUMBER(5,2), 
	"REGISTER_DATE" DATE, 
	"SHIPPING" VARCHAR2(20), 
	 PRIMARY KEY ("PRODUCT_CODE")
   );




CREATE TABLE "CUSTOMERS" 
   (	"CUSTOMER_CODE" NUMBER(6,0), 
	"CUSTOMER_NAME" VARCHAR2(20) NOT NULL ENABLE, 
	"CUSTOMER_ID" VARCHAR2(20) NOT NULL ENABLE, 
	"ADDRESS" VARCHAR2(100) NOT NULL ENABLE, 
	"PHONE" VARCHAR2(20) NOT NULL ENABLE, 
	"ZIP_CODE" VARCHAR2(10) NOT NULL ENABLE, 
	"CUSTOM_CLEARANCE_CODE" VARCHAR2(20), 
	 PRIMARY KEY ("CUSTOMER_CODE")
   );
 



  CREATE TABLE "SALES" 
   (	"SALES_CODE" NUMBER(6,0), 
	"SALES_DATE" DATE, 
	"ORDER_DATE" DATE, 
	"SHIP_DATE" DATE, 
	"CUSTOMER_CODE" NUMBER(6,0), 
	"PAYMENT" NUMBER(7,0), 
	"MESSAGE" VARCHAR2(100), 
	"PLATFORM" VARCHAR2(20), 
	"NOTE" VARCHAR2(100), 
	 PRIMARY KEY ("SALES_CODE"),
	 CONSTRAINT "SALES_FK" FOREIGN KEY ("CUSTOMER_CODE")
	 REFERENCES "KOSEA"."CUSTOMERS" ("CUSTOMER_CODE") ENABLE
   );
 




  CREATE TABLE "SALES_DETAILS" 
   (	"SALES_CODE" NUMBER(6,0), 
	"PRODUCT_CODE" NUMBER(5,0), 
	"PURCHASE_AMOUNT" NUMBER(3,0), 
	"REFUND_AMOUNT" NUMBER(3,0) DEFAULT 0, 
	 CONSTRAINT "SD_PK" PRIMARY KEY ("SALES_CODE", "PRODUCT_CODE"), 
	 CONSTRAINT "SD_FK2" FOREIGN KEY ("PRODUCT_CODE")
	  REFERENCES "PRODUCTS" ("PRODUCT_CODE") ENABLE, 
	 CONSTRAINT "SD_FK1" FOREIGN KEY ("SALES_CODE")
	  REFERENCES "SALES" ("SALES_CODE") ON DELETE CASCADE ENABLE
   );
 